import _4pions from "./4pions.png";
import _PortraitChinois from "./PortraitChinois.png";
import _Problemes from "./Problemes.png";
import _ProdEcrits from "./ProdEcrits.png";
import _abaque from "./abaque.png";
import _abaques_taquins from "./abaques-taquins.png";
import _acrostiche from "./acrostiche.png";
import _addigrille from "./addigrille.png";
import _additions from "./additions.png";
import _alea_cartes from "./alea-cartes.png";
import _alphabet from "./alphabet.png";
import _anagrammes from "./anagrammes.png";
import _angles from "./angles.png";
import _animations from "./animations.png";
import _arborescence from "./arborescence.png";
import _ardoise from "./ardoise.png";
import _audio_tag from "./audio-tag.png";
import _awarhol from "./awarhol.png";
import _barres_doigts from "./barres-doigts.png";
import _bataille from "./bataille.png";
import _blog from "./blog.png";
import _boulier from "./boulier.png";
import _boulierHTML5 from "./boulierHTML5.png";
import _calculmental from "./calculmental.png";
import _cambridge from "./cambridge.png";
import _cartapoints from "./cartapoints.png";
import _chateau from "./chateau.png";
import _chemins_de_phrases from "./chemins-de-phrases.png";
import _choixpeau from "./choixpeau.png";
import _cibles from "./cibles.png";
import _classement from "./classement.png";
import _clavier from "./clavier.png";
import _cologrilles from "./cologrilles.png";
import _cologrillesgenerateur from "./cologrillesgenerateur.png";
import _complements from "./complements.png";
import _compter from "./compter.png";
import _compteur from "./compteur.png";
import _conjugaison from "./conjugaison.png";
import _conversion from "./conversion.png";
import _conversion2 from "./conversion2.png";
import _conversions from "./conversions.png";
import _courseau21 from "./courseau21.png";
import _decimaux from "./decimaux.png";
import _denombrement from "./denombrement.png";
import _dictee from "./dictee.png";
import _dicteenombres from "./dicteenombres.png";
import _didapages from "./didapages.png";
import _differences from "./differences.png";
import _discrimination from "./discrimination.png";
import _divisator from "./divisator.png";
import _dominos from "./dominos.png";
import _eacrostiches from "./eacrostiches.png";
import _ecoute_et_range from "./ecoute-et-range.png";
import _ecrans_ipad from "./ecrans-ipad.png";
import _edidafusion from "./edidafusion.png";
import _embouteillages from "./embouteillages.png";
import _etiquettes_virtuelles from "./etiquettes-virtuelles.png";
import _etiquettes from "./etiquettes.png";
import _fabricamo from "./fabricamo.png";
import _fabriquehistoires from "./fabriquehistoires.png";
import _flipflap from "./flipflap.png";
import _fractions_generateur from "./fractions-generateur.png";
import _fractions from "./fractions.png";
import _frise_circulaire from "./frise-circulaire.png";
import _frise from "./frise.png";
import _fusionLignes from "./fusionLignes.png";
import _fusionddp from "./fusionddp.png";
import _gabuzomeu from "./gabuzomeu.png";
import _graduations from "./graduations.png";
import _groupements from "./groupements.png";
import _hashtagfrom from "./hashtagfrom.png";
import _homophones from "./homophones.png";
import _images_sequentielles from "./images-sequentielles.png";
import _imagesetsons from "./imagesetsons.png";
import _jeux_lecture from "./jeux-lecture.png";
import _jeux_mathematiques_1 from "./jeux-mathematiques-1.png";
import _jeux_mathematiques_2 from "./jeux-mathematiques-2.png";
import _jeux_mathematiques from "./jeux-mathematiques.png";
import _la_bonne_image from "./la-bonne-image.png";
import _labyrinthes_pdf from "./labyrinthes-pdf.png";
import _labyrinthes from "./labyrinthes.png";
import _le_bon_mot from "./le-bon-mot.png";
import _lecture_heure_generateur from "./lecture-heure-generateur.png";
import _lecture_heure from "./lecture-heure.png";
import _logitic from "./logitic.png";
import _logixourriel from "./logixourriel.png";
import _loto from "./loto.png";
import _mastermind from "./mastermind.png";
import _mdp_gen from "./mdp-gen.png";
import _media_folder_generator from "./media-folder-generator.png";
import _meme_indice from "./meme-indice.png";
import _memory_generateur from "./memory-generateur.png";
import _memory from "./memory.png";
import _messagerie from "./messagerie.png";
import _mesures from "./mesures.png";
import _minuterie from "./minuterie.png";
import _montessori from "./montessori.png";
import _mosaique from "./mosaique.png";
import _multiplication from "./multiplication.png";
import _nombre_pense from "./nombre-pense.png";
import _nombres from "./nombres.png";
import _np2016 from "./np2016.png";
import _numeration from "./numeration.png";
import _numop from "./numop.png";
import _operations from "./operations.png";
import _ordonner from "./ordonner.png";
import _ordre_alpha from "./ordre-alpha.png";
import _orlf from "./orlf.png";
import _ortho_lex from "./ortho-lex.png";
import _orthographe from "./orthographe.png";
import _outilstice from "./outilstice.png";
import _papota2 from "./papota2.png";
import _parachute from "./parachute.png";
import _parapente from "./parapente.png";
import _parcours_de_phrases from "./parcours-de-phrases.png";
import _parking from "./parking.png";
import _pense from "./pense.png";
import _phonologie from "./phonologie.png";
import _phrases from "./phrases.png";
import _picbille from "./picbille.png";
import _picturetopuzzle from "./picturetopuzzle.png";
import _pourquoiparceque from "./pourquoiparceque.png";
import _puissance10 from "./puissance10.png";
import _qrcode from "./qrcode.png";
import _quadrillage from "./quadrillage.png";
import _rallye_lecture from "./rallye-lecture.png";
import _rcn2017 from "./rcn2017.png";
import _recadrer from "./recadrer.png";
import _reperage from "./reperage.png";
import _reussites from "./reussites.png";
import _robots from "./robots.png";
import _rounded_word_cards from "./rounded-word-cards.png";
import _rounded_word from "./rounded-word.png";
import _rsq from "./rsq.png";
import _rsqgenerateur from "./rsqgenerateur.png";
import _ruche_mots from "./ruche-mots.png";
import _ruche_nombres from "./ruche-nombres.png";
import _sciences from "./sciences.png";
import _scrabble from "./scrabble.png";
import _sept_familles from "./sept-familles.png";
import _sig from "./sig.png";
import _simulation_salaire from "./simulation-salaire.png";
import _souris from "./souris.png";
import _ssq from "./ssq.png";
import _ssqgenerateur from "./ssqgenerateur.png";
import _sudoku from "./sudoku.png";
import _superpositions from "./superpositions.png";
import _symbole_commun from "./symbole-commun.png";
import _symetrie from "./symetrie.png";
import _tables_addition from "./tables-addition.png";
import _tables_division from "./tables-division.png";
import _tables_multiplication from "./tables-multiplication.png";
import _tables_soustraction from "./tables-soustraction.png";
import _tempsquireste from "./tempsquireste.png";
import _thermometre from "./thermometre.png";
import _tutos from "./tutos.png";
import _vehicules from "./vehicules.png";
import _video_tag from "./video-tag.png";
import _vocatego from "./vocatego.png";
import _wpprezi from "./wpprezi.png";
import _youtube from "./youtube.png";
import _ytsearch from "./ytsearch.png";
export const _4PIONS = _4pions;
export const _PORTRAITCHINOIS = _PortraitChinois;
export const _PROBLEMES = _Problemes;
export const _PRODECRITS = _ProdEcrits;
export const _ABAQUE = _abaque;
export const _ABAQUES_TAQUINS = _abaques_taquins;
export const _ACROSTICHE = _acrostiche;
export const _ADDIGRILLE = _addigrille;
export const _ADDITIONS = _additions;
export const _ALEA_CARTES = _alea_cartes;
export const _ALPHABET = _alphabet;
export const _ANAGRAMMES = _anagrammes;
export const _ANGLES = _angles;
export const _ANIMATIONS = _animations;
export const _ARBORESCENCE = _arborescence;
export const _ARDOISE = _ardoise;
export const _AUDIO_TAG = _audio_tag;
export const _AWARHOL = _awarhol;
export const _BARRES_DOIGTS = _barres_doigts;
export const _BATAILLE = _bataille;
export const _BLOG = _blog;
export const _BOULIER = _boulier;
export const _BOULIERHTML5 = _boulierHTML5;
export const _CALCULMENTAL = _calculmental;
export const _CAMBRIDGE = _cambridge;
export const _CARTAPOINTS = _cartapoints;
export const _CHATEAU = _chateau;
export const _CHEMINS_DE_PHRASES = _chemins_de_phrases;
export const _CHOIXPEAU = _choixpeau;
export const _CIBLES = _cibles;
export const _CLASSEMENT = _classement;
export const _CLAVIER = _clavier;
export const _COLOGRILLES = _cologrilles;
export const _COLOGRILLESGENERATEUR = _cologrillesgenerateur;
export const _COMPLEMENTS = _complements;
export const _COMPTER = _compter;
export const _COMPTEUR = _compteur;
export const _CONJUGAISON = _conjugaison;
export const _CONVERSION = _conversion;
export const _CONVERSION2 = _conversion2;
export const _CONVERSIONS = _conversions;
export const _COURSEAU21 = _courseau21;
export const _DECIMAUX = _decimaux;
export const _DENOMBREMENT = _denombrement;
export const _DICTEE = _dictee;
export const _DICTEENOMBRES = _dicteenombres;
export const _DIDAPAGES = _didapages;
export const _DIFFERENCES = _differences;
export const _DISCRIMINATION = _discrimination;
export const _DIVISATOR = _divisator;
export const _DOMINOS = _dominos;
export const _EACROSTICHES = _eacrostiches;
export const _ECOUTE_ET_RANGE = _ecoute_et_range;
export const _ECRANS_IPAD = _ecrans_ipad;
export const _EDIDAFUSION = _edidafusion;
export const _EMBOUTEILLAGES = _embouteillages;
export const _ETIQUETTES_VIRTUELLES = _etiquettes_virtuelles;
export const _ETIQUETTES = _etiquettes;
export const _FABRICAMO = _fabricamo;
export const _FABRIQUEHISTOIRES = _fabriquehistoires;
export const _FLIPFLAP = _flipflap;
export const _FRACTIONS_GENERATEUR = _fractions_generateur;
export const _FRACTIONS = _fractions;
export const _FRISE_CIRCULAIRE = _frise_circulaire;
export const _FRISE = _frise;
export const _FUSIONLIGNES = _fusionLignes;
export const _FUSIONDDP = _fusionddp;
export const _GABUZOMEU = _gabuzomeu;
export const _GRADUATIONS = _graduations;
export const _GROUPEMENTS = _groupements;
export const _HASHTAGFROM = _hashtagfrom;
export const _HOMOPHONES = _homophones;
export const _IMAGES_SEQUENTIELLES = _images_sequentielles;
export const _IMAGESETSONS = _imagesetsons;
export const _JEUX_LECTURE = _jeux_lecture;
export const _JEUX_MATHEMATIQUES_1 = _jeux_mathematiques_1;
export const _JEUX_MATHEMATIQUES_2 = _jeux_mathematiques_2;
export const _JEUX_MATHEMATIQUES = _jeux_mathematiques;
export const _LA_BONNE_IMAGE = _la_bonne_image;
export const _LABYRINTHES_PDF = _labyrinthes_pdf;
export const _LABYRINTHES = _labyrinthes;
export const _LE_BON_MOT = _le_bon_mot;
export const _LECTURE_HEURE_GENERATEUR = _lecture_heure_generateur;
export const _LECTURE_HEURE = _lecture_heure;
export const _LOGITIC = _logitic;
export const _LOGIXOURRIEL = _logixourriel;
export const _LOTO = _loto;
export const _MASTERMIND = _mastermind;
export const _MDP_GEN = _mdp_gen;
export const _MEDIA_FOLDER_GENERATOR = _media_folder_generator;
export const _MEME_INDICE = _meme_indice;
export const _MEMORY_GENERATEUR = _memory_generateur;
export const _MEMORY = _memory;
export const _MESSAGERIE = _messagerie;
export const _MESURES = _mesures;
export const _MINUTERIE = _minuterie;
export const _MONTESSORI = _montessori;
export const _MOSAIQUE = _mosaique;
export const _MULTIPLICATION = _multiplication;
export const _NOMBRE_PENSE = _nombre_pense;
export const _NOMBRES = _nombres;
export const _NP2016 = _np2016;
export const _NUMERATION = _numeration;
export const _NUMOP = _numop;
export const _OPERATIONS = _operations;
export const _ORDONNER = _ordonner;
export const _ORDRE_ALPHA = _ordre_alpha;
export const _ORLF = _orlf;
export const _ORTHO_LEX = _ortho_lex;
export const _ORTHOGRAPHE = _orthographe;
export const _OUTILSTICE = _outilstice;
export const _PAPOTA2 = _papota2;
export const _PARACHUTE = _parachute;
export const _PARAPENTE = _parapente;
export const _PARCOURS_DE_PHRASES = _parcours_de_phrases;
export const _PARKING = _parking;
export const _PENSE = _pense;
export const _PHONOLOGIE = _phonologie;
export const _PHRASES = _phrases;
export const _PICBILLE = _picbille;
export const _PICTURETOPUZZLE = _picturetopuzzle;
export const _POURQUOIPARCEQUE = _pourquoiparceque;
export const _PUISSANCE10 = _puissance10;
export const _QRCODE = _qrcode;
export const _QUADRILLAGE = _quadrillage;
export const _RALLYE_LECTURE = _rallye_lecture;
export const _RCN2017 = _rcn2017;
export const _RECADRER = _recadrer;
export const _REPERAGE = _reperage;
export const _REUSSITES = _reussites;
export const _ROBOTS = _robots;
export const _ROUNDED_WORD_CARDS = _rounded_word_cards;
export const _ROUNDED_WORD = _rounded_word;
export const _RSQ = _rsq;
export const _RSQGENERATEUR = _rsqgenerateur;
export const _RUCHE_MOTS = _ruche_mots;
export const _RUCHE_NOMBRES = _ruche_nombres;
export const _SCIENCES = _sciences;
export const _SCRABBLE = _scrabble;
export const _SEPT_FAMILLES = _sept_familles;
export const _SIG = _sig;
export const _SIMULATION_SALAIRE = _simulation_salaire;
export const _SOURIS = _souris;
export const _SSQ = _ssq;
export const _SSQGENERATEUR = _ssqgenerateur;
export const _SUDOKU = _sudoku;
export const _SUPERPOSITIONS = _superpositions;
export const _SYMBOLE_COMMUN = _symbole_commun;
export const _SYMETRIE = _symetrie;
export const _TABLES_ADDITION = _tables_addition;
export const _TABLES_DIVISION = _tables_division;
export const _TABLES_MULTIPLICATION = _tables_multiplication;
export const _TABLES_SOUSTRACTION = _tables_soustraction;
export const _TEMPSQUIRESTE = _tempsquireste;
export const _THERMOMETRE = _thermometre;
export const _TUTOS = _tutos;
export const _VEHICULES = _vehicules;
export const _VIDEO_TAG = _video_tag;
export const _VOCATEGO = _vocatego;
export const _WPPREZI = _wpprezi;
export const _YOUTUBE = _youtube;
export const _YTSEARCH = _ytsearch;
