import * as thumbnail from "./thumbnails";

export default {
    byId: {
        abaque: {
            id: "abaque",
            title: "Abaque",
            url: "abaque",
            description:
                "Abaque virtuel permettant de travailler la numération à l'école primaire.",
            thumbnail: thumbnail._ABAQUE,
            keywords: [
                "abaque",
                "maths",
                "mathématique",
                "numération",
                "nombre",
            ],
        },
        abataquin: {
            id: "abataquin",
            title: "Abaques-taquins",
            url: "abataquin",
            description:
                "Jeu interactif dont le but est de déplacer les boules d'un abaque de départ pour obtenir la même disposition que sur un abaque d'arrivée.",
            thumbnail: thumbnail._ABAQUES_TAQUINS,
            keywords: ["abaques-taquins", "maths", "mathématique"],
        },
        acrostiche: {
            id: "acrostiche",
            title: "Acrostiches",
            url: "acrostiche",
            description: `Application web permettant de créer des images'acrostiches.`,
            thumbnail: thumbnail._ACROSTICHE,
            keywords: ["acrostiches", "français", "écrit"],
        },
        addigrille: {
            id: "addigrille",
            title: "Addi-Grilles 2.0",
            url: "addigrille",
            description: `Application web permettant de travailler le calcul à l'école primaire en réalisant des Addi-Grilles en ligne.`,
            thumbnail: thumbnail._ADDIGRILLE,
            keywords: ["addi-grilles", "calcul", "maths", "mathématique"],
        },
        addition: {
            id: "addition",
            title: "Additions",
            url: "addition",
            description: `Application web permettant de s'exercer au calcul de sommes d'entiers inférieurs à 10.`,
            thumbnail: thumbnail._ADDITIONS,
            keywords: [
                "additions",
                "calcul",
                "maths",
                "mathématique",
                "opération",
            ],
        },
        alphabet: {
            id: "alphabet",
            title: "Alphabet",
            url: "alphabet",
            description: `Application web permettant de manipuler les lettres de l'alphabet.`,
            thumbnail: thumbnail._ALPHABET,
            keywords: ["alphabet", "lecture", "français", "écriture"],
        },
        anagrammes: {
            id: "anagrammes",
            title: "Anagrammes",
            url: "anagrammes",
            description: `Application web permettant de proposer des anagrammes à partir d'un corpus de mots.`,
            thumbnail: thumbnail._ANAGRAMMES,
            keywords: ["anagrammes", "lecture", "français", "écriture"],
        },
        angles: {
            id: "angles",
            title: "Angles",
            url: "angles",
            description: `Application web permettant de générer des images d'angles.`,
            thumbnail: thumbnail._ANGLES,
            keywords: [
                "angles",
                "maths",
                "mathématique",
                "générateur",
                "géométrie",
            ],
        },
        animations: {
            id: "animations",
            title: "Animations",
            url: "animations",
            description: `Bilbliothèques d'animations réalisées en HTML5.`,
            thumbnail: thumbnail._ANIMATIONS,
            keywords: ["animations", "français", "récit", "poésie"],
        },
        arborescence: {
            id: "arborescence",
            title: "Arborescence",
            url: "arborescence",
            description: `Application web permettant de générer un dossier contenant une arborescence donnée de dossiers.`,
            thumbnail: thumbnail._ARBORESCENCE,
            keywords: ["arborescence", "informatique", "divers"],
        },
        ardoise: {
            id: "ardoise",
            title: "Ardoise",
            url: "ardoise",
            description: `Application web proposant une ardoise utilisable sur une tablette.`,
            thumbnail: thumbnail._ARDOISE,
            keywords: ["ardoise", "tablette", "dessin", "divers"],
        },
        awarhol: {
            id: "awarhol",
            title: "Andy Warhol",
            url: "awarhol",
            description: `Application web permettant de générer une image à la manière d'Andy Warhol à partir de sa propre image.`,
            thumbnail: thumbnail._AWARHOL,
            keywords: ["awarhol", "warhol", "andy", "arts", "divers"],
        },
        "audio-tag": {
            id: "audio-tag",
            title: "Audio Tag",
            url: "audio-tag",
            description: `Application web permettant de générer automatiquement le code avec la balise <audio> nécessaire à l'insertion d'une vidéo dans une page html5.`,
            thumbnail: thumbnail._AUDIO_TAG,
            keywords: [
                "audio",
                "balise",
                "tag",
                "générateur",
                "outil",
                "html5",
                "divers",
            ],
        },
        "barres-doigts": {
            id: "barres-doigts",
            title: "Barres-doigts",
            url: "barres-doigts",
            description: `Application web permettant de manipuler les constellations de doigts barres de Stella Baruk.`,
            thumbnail: thumbnail._BARRES_DOIGTS,
            keywords: [
                "barres-doigts",
                "numération",
                "stella",
                "baruk",
                "maths",
                "mathématiques",
            ],
        },
        bataille: {
            id: "bataille",
            title: "Bataille",
            url: "bataille",
            description: `Application web permettant de générer des jeux de bataille à partir d'une image de son ordinateur.`,
            thumbnail: thumbnail._BATAILLE,
            keywords: ["bataille", "générateur", "carte", "divers"],
        },
        blog: {
            id: "blog",
            title: "Blog",
            url: "blog",
            description: `Blog associé au site micetf.fr.`,
            thumbnail: thumbnail._BLOG,
            keywords: ["blog", "pratique", "théorique", "technique", "divers"],
        },
        boulierHTML5: {
            id: "boulierHTML5",
            title: "Boulier (1)",
            url: "boulierHTML5",
            description: `Boulier virtuel permettant de travailler la numération à l'école primaire.`,
            thumbnail: thumbnail._BOULIERHTML5,
            keywords: [
                "boulier",
                "maths",
                "mathématiques",
                "numération",
                "nombre",
                "opérations",
            ],
        },
        boulier: {
            id: "boulier",
            title: "Boulier (2)",
            url: "boulier",
            description: `Boulier virtuel permettant de travailler la numération à l'école primaire.`,
            thumbnail: thumbnail._BOULIER,
            keywords: [
                "boulier",
                "maths",
                "mathématiques",
                "numération",
                "nombre",
                "opérations",
            ],
        },
        rcn2017: {
            id: "rcn2017",
            title: "Compétences Numériques (Projet mars 2017)",
            url: "rcn2017",
            description: `Projet en consultation entre février et avril 2017 : Cadre de référence des compétences numériques.`,
            thumbnail: thumbnail._RCN2017,
            keywords: [
                "cadre",
                "référence",
                "divers",
                "compétences",
                "numériques",
                "information",
                "données",
                "communication",
                "collaboration",
                "création",
                "contenu",
                "protection",
                "sécurité",
                "environnement",
            ],
        },
        calculmental: {
            id: "calculmental",
            title: "Calcul Mental",
            url: "calculmental",
            description: `Application web proposant des exercices de calcul mental du CP au CM2. Les élèves peuvent réaliser ces exercices en ligne. Les enseignants peuvent générer et imprimer ces exercices au format pdf.`,
            thumbnail: thumbnail._CALCULMENTAL,
            keywords: [
                "calcul mental",
                "maths",
                "mathématiques",
                "numération",
                "nombre",
                "opérations",
            ],
        },
        cambridge: {
            id: "cambridge",
            title: "Cambridge (Dégradation de)",
            url: "cambridge",
            description: `Application web permettant d'appliquer la dégradation de Cambridge à n'importe quel texte.`,
            thumbnail: thumbnail._CAMBRIDGE,
            keywords: ["cambridge", "dégradation", "divers", "français"],
        },
        cartapoints: {
            id: "cartapoints",
            title: "Cartes à points",
            url: "cartapoints",
            description: `Application web permettant de générer des images de cartes à points pour travailler la numératio'école primaire.`,
            thumbnail: thumbnail._CARTAPOINTS,
            keywords: [
                "cartes",
                "points",
                "générateur",
                "maths",
                "mathématiques",
                "numération",
                "nombre",
            ],
        },
        "alea-cartes": {
            id: "alea-cartes",
            title: "Cartes aléatoires",
            url: "alea-cartes",
            description: `Application web permettant de préparer des cartes et de gérer un tirage aléatoire interactif.`,
            thumbnail: thumbnail._ALEA_CARTES,
            keywords: ["aléatoire", "cartes", "divers", "tirage", "outil"],
        },
        chateau: {
            id: "chateau",
            title: "Château des nombres",
            url: "chateau",
            description: `Application web proposant un château des nombres interactif pour travailler la numération à l'école primaire.`,
            thumbnail: thumbnail._CHATEAU,
            keywords: [
                "chateau des nombres",
                "maths",
                "mathématiques",
                "numération",
                "nombre",
            ],
        },
        "chemins-de-phrases": {
            id: "chemins-de-phrases",
            title: "Chemins de phrases",
            url: "chemins-de-phrases",
            description: `Jeu interactif dont le but est de retrouver dans un tableau le chemin (multi-directions) qui permet de reconstruire une phrase juste.`,
            thumbnail: thumbnail._CHEMINS_DE_PHRASES,
            keywords: ["chemins de phrases", "français", "orthographe"],
        },
        choixpeau: {
            id: "choixpeau",
            title: "Choixpeau magique",
            url: "choixpeau",
            description: `Application web permettant de réaliser un tirage aléatoire à partir d'une liste de mots ou d'images.`,
            thumbnail: thumbnail._CHOIXPEAU,
            keywords: [
                "choixpeau magique",
                "divers",
                "magique",
                "aléatoire",
                "tirage",
            ],
        },
        cibles: {
            id: "cibles",
            title: "Cibles (Jeu des)",
            url: "cibles",
            description: `Jeu interactif pour travailler la décomposition additive des nombres à l'école primaire.`,
            thumbnail: thumbnail._CIBLES,
            keywords: [
                "cibles",
                "jeu",
                "maths",
                "mathématiques",
                "nombre",
                "numération",
            ],
        },
        classement: {
            id: "classement",
            title: "Classement",
            url: "classement",
            description: `Application web permettant de réaliser des activités de tri au vidéo-projecteur et de conserver une trace numérique de ces travaux.`,
            thumbnail: thumbnail._CLASSEMENT,
            keywords: [
                "classement",
                "divers",
                "tbi",
                "vidéo-projecteur",
                "tni",
                "outil",
            ],
        },
        clavier: {
            id: "clavier",
            title: "Clavier (Les As du)",
            url: "clavier",
            description: `Jeu interactif permettant de travailler la maîtrise du clavier à l'école primaire.`,
            thumbnail: thumbnail._CLAVIER,
            keywords: ["clavier", "as", "tuic", "divers", "saisie"],
        },
        cologrilles: {
            id: "cologrilles",
            title: "Coloriage sur Quadrillages",
            url: "cologrilles",
            description: `Application web proposant de reproduire des coloriages sur des quadrillages.`,
            thumbnail: thumbnail._COLOGRILLES,
            keywords: [
                "cologrilles",
                "coloriage",
                "quadrillage",
                "maths",
                "mathématiques",
                "géométrie",
            ],
        },
        cologrillesgenerateur: {
            id: "cologrillesgenerateur",
            title: "Coloriage sur Quadrillages (Générateur)",
            url: "cologrillesgenerateur",
            description: `Application web proposant de créer et d'imprimer des coloriages sur quadrillages.`,
            thumbnail: thumbnail._COLOGRILLESGENERATEUR,
            keywords: [
                "cologrilles",
                "coloriage",
                "quadrillage",
                "générateur",
                "maths",
                "mathématiques",
                "géométrie",
            ],
        },
        complements: {
            id: "complements",
            title: "Compléments à 10, 100 ou 1000",
            url: "complements",
            description: `Jeu interactif permettant de s'exercer au calcul des compléments à 10, 100 ou 1000.`,
            thumbnail: thumbnail._COMPLEMENTS,
            keywords: [
                "compléments",
                "numération",
                "nombres",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        compter: {
            id: "compter",
            title: "Compter",
            url: "compter",
            description: `Livre des nombres.`,
            thumbnail: thumbnail._COMPTER,
            keywords: [
                "compter",
                "numération",
                "nombres",
                "livre des nombres",
                "maths",
                "mathématiques",
            ],
        },
        Compteur: {
            id: "Compteur",
            title: "Compteur",
            url: "Compteur",
            description: `Compteur interactif.`,
            thumbnail: thumbnail._COMPTEUR,
            keywords: [
                "compteur",
                "numération",
                "nombres",
                "maths",
                "mathématiques",
            ],
        },
        conjugaison: {
            id: "conjugaison",
            title: "Conjugaison (Générateur)",
            url: "conjugaison",
            description: `Générateur d'exercices de conjugaison au format pdf.`,
            thumbnail: thumbnail._CONJUGAISON,
            keywords: [
                "conjugaison",
                "français",
                "maîtrise",
                "générateur",
                "verbes",
            ],
        },
        Conversions: {
            id: "Conversions",
            title: "Conversion (v1)",
            url: "Conversions",
            description: `Tableau de conversion (interactif) d'unités de mesure de longueur (m), de masse (g) et de volume (l).`,
            thumbnail: thumbnail._CONVERSIONS,
            keywords: ["conversions", "maths", "unités", "mesures", "grandeur"],
        },
        conversion: {
            id: "conversion",
            title: "Conversion (v2)",
            url: "conversion",
            description: `Tableau de conversion (interactif) d'unités de mesure de longueur (m), de masse (g) et de volume (l).`,
            thumbnail: thumbnail._CONVERSION,
            keywords: ["conversions", "maths", "unités", "mesures", "grandeur"],
        },
        conversion2: {
            id: "conversion2",
            title: "Conversion (surfaces)",
            url: "conversion2",
            description: `Tableau de conversion (interactif) d'unité de mesures de surface (m²).`,
            thumbnail: thumbnail._CONVERSION2,
            keywords: [
                "conversions",
                "maths",
                "unités",
                "mesures",
                "grandeur",
                "surfaces",
                "aires",
            ],
        },
        CourseAu21: {
            id: "CourseAu21",
            title: "Course au 21",
            url: "CourseAu21",
            description: `Jeu interactif permettant de jouer à 2 personnes à la course au 21.`,
            thumbnail: thumbnail._COURSEAU21,
            keywords: [
                "logique",
                "maths",
                "problème",
                "algorithme",
                "mathématiques",
                "course au 21",
            ],
        },
        decimaux: {
            id: "decimaux",
            title: "Décimaux",
            url: "decimaux",
            description: `Application web permettant de travailler les écritures et les représentations des nombres décimaux.`,
            thumbnail: thumbnail._DECIMAUX,
            keywords: [
                "décimaux",
                "maths",
                "numération",
                "nombres",
                "mathématiques",
                "représentations",
            ],
        },
        Denombrement: {
            id: "Denombrement",
            title: "Dénombrement",
            url: "Denombrement",
            description: `Application web permettant de travailler les écritures et les représentations des nombres décimaux.`,
            thumbnail: thumbnail._DENOMBREMENT,
            keywords: [
                "dénombrement",
                "maths",
                "numération",
                "nombres",
                "mathématiques",
            ],
        },
        Didapages: {
            id: "Didapages",
            title: "Didapages (fusion)",
            url: "Didapages",
            description: `Application web (Première Version) permettant la fusion de plusieurs petits livres interactifs créés avec Didapages.`,
            thumbnail: thumbnail._DIDAPAGES,
            keywords: [
                "didapages",
                "livres",
                "numériques",
                "divers",
                "fusion",
                "tuic",
            ],
        },
        divisator: {
            id: "divisator",
            title: "Divisator",
            url: "divisator",
            description: `Application web permettant de s'exercer à la recherche du quotient et du reste de divisions simples.`,
            thumbnail: thumbnail._DIVISATOR,
            keywords: [
                "divisator",
                "maths",
                "mathématiques",
                "calcul mental",
                "division",
                "tables",
                "multiplication",
            ],
        },
        Dominos: {
            id: "Dominos",
            title: "Dominos",
            url: "Dominos",
            description: `Application web permettant la génération de jeux de dominos additifs ou multiplicatifs au format pdf.`,
            thumbnail: thumbnail._DOMINOS,
            keywords: [
                "dominos",
                "maths",
                "mathématiques",
                "calcul mental",
                "addition",
                "tables",
                "multiplication",
            ],
        },
        dictee: {
            id: "dictee",
            title: "Dictées (Je crée mes dictées)",
            url: "dictee",
            description: `Application web permettant aux enseignants de créer des dictées.`,
            thumbnail: thumbnail._DICTEE,
            keywords: ["dictées", "orthographe", "français"],
        },
        dicteenombres: {
            id: "dicteenombres",
            title: "Dictée de nombres",
            url: "dicteenombres",
            description: `Jeu interactif permettant de s'exercer à l'écriture chiffrée de nombres dictés.`,
            thumbnail: thumbnail._DICTEENOMBRES,
            keywords: [
                "dictées",
                "nombres",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        differences: {
            id: "differences",
            title: "Différences en GS de maternelle",
            url: "differences",
            description: `Jeu interactif reprenant l'activité du même nom proposée par D. Valentin pour les GS.`,
            thumbnail: thumbnail._DIFFERENCES,
            keywords: [
                "différences",
                "logique",
                "résolution",
                "problèmes",
                "maths",
                "mathématiques",
                "valentin",
            ],
        },
        discrimination: {
            id: "discrimination",
            title: "Discrimination visuelle",
            url: "discrimination",
            description: `Jeu interactif permettant d'exercer sa discrimination visuelle pour améliorer sa vitesse de lecture.`,
            thumbnail: thumbnail._DISCRIMINATION,
            keywords: ["discrimination visuelle", "lecture", "français"],
        },
        eAcrostiches: {
            id: "eAcrostiches",
            title: "e-Acrostiches",
            url: "eAcrostiches",
            description: `Application web permettant de créer des images'acrostiches.`,
            thumbnail: thumbnail._EACROSTICHES,
            keywords: ["acrostiche", "écrit", "français"],
        },
        eDidaFusion: {
            id: "eDidaFusion",
            title: "e-Didafusion",
            url: "eDidaFusion",
            description: `Application web (Deuxième Version) permettant la fusion de plusieurs petits livres interactifs créés avec Didapages.`,
            thumbnail: thumbnail._EDIDAFUSION,
            keywords: [
                "didapages",
                "livres",
                "numériques",
                "divers",
                "fusion",
                "tuic",
            ],
        },
        "ecrans-ipad": {
            id: "ecrans-ipad",
            title: "Ecrans pour iPad (Générateur)",
            url: "ecrans-ipad",
            description: `Générer des fonds d'écrans (écran verrouillé et/ou écran d'accueil) pour identifier les différentes tablettes de la classe.`,
            thumbnail: thumbnail._ECRANS_IPAD,
            keywords: [
                "générateur",
                "écran",
                "divers",
                "fond",
                "ipad",
                "iPad",
                "tablettes",
                "astuce",
            ],
        },
        Embouteillages: {
            id: "Embouteillages",
            title: "Embouteillages en GS de maternelle",
            url: "Embouteillages",
            description: `Jeu interactif reprenant l'activité du même nom proposée par D. Valentin pour les GS.`,
            thumbnail: thumbnail._EMBOUTEILLAGES,
            keywords: [
                "embouteillages",
                "logique",
                "résolution",
                "problèmes",
                "maths",
                "mathématiques",
                "valentin",
            ],
        },
        Etiquettes: {
            id: "Etiquettes",
            title: "Etiquettes",
            url: "Etiquettes",
            description: `Application web permettant, à partir d'une série de mots, de générer des étiquettes au format image archivées un dossier.`,
            thumbnail: thumbnail._ETIQUETTES,
            keywords: ["etiquettes", "tuic", "divers", "générateur"],
        },
        eEtiquettes: {
            id: "eEtiquettes",
            title: "Etiquettes virtuelles",
            url: "eEtiquettes",
            description: `Application web permettant, à partir d'une série de mots, de générer des étiquettes au format image archivées un dossier. Cette version plus complexe que la précédente offre cependant plus de fonctionnalités.`,
            thumbnail: thumbnail._ETIQUETTES_VIRTUELLES,
            keywords: ["etiquettes", "tuic", "divers", "générateur"],
        },
        "ecoute-et-range": {
            id: "ecoute-et-range",
            title: "Ecoute et range",
            url: "ecoute-et-range",
            description: `Application web permettant d'entraînement à la compréhension d'histoire. Cette application aurait tout aussi bien s'appeler range et écoute.`,
            thumbnail: thumbnail._ECOUTE_ET_RANGE,
            keywords: ["lecture", "compréhension", "français"],
        },
        FaBriCaMo: {
            id: "FaBriCaMo",
            title: "Fa Bri Ca Mo",
            url: "FaBriCaMo",
            description: `Prototype d'une application web permettant d'accompagner les élèves dans la découverte de l'encodage des mots au CP.`,
            thumbnail: thumbnail._FABRICAMO,
            keywords: [
                "fabricamo",
                "lecture",
                "syllabes",
                "décodage",
                "encodage",
                "français",
            ],
        },
        FabriqueHistoires: {
            id: "FabriqueHistoires",
            title: "FabriqueHistoires",
            url: "FabriqueHistoires",
            description: `Application web permettant la création de petits livres interactifs sur le principe de "Ma Petite Fabrique à Histoires" de Bruno Gibert.`,
            thumbnail: thumbnail._FABRIQUEHISTOIRES,
            keywords: ["écrit", "histoires", "gibert", "fabrique", "français"],
        },
        FabriquePourquoiParceque: {
            id: "FabriquePourquoiParceque",
            title: 'Fabrique de "Pourquoi ? Parce que !"',
            url: "FabriquePourquoiParceque",
            description: `Application web permettant la création de petits livres interactifs sur le thème des "Pourquoi ? Parce que ?".`,
            thumbnail: thumbnail._POURQUOIPARCEQUE,
            keywords: [
                "écrit",
                "histoires",
                "gibert",
                "fabrique",
                "français",
                "pourquoi",
                "parce que",
            ],
        },
        Flipflap: {
            id: "Flipflap",
            title: "Flip Flap Fred",
            url: "Flipflap",
            description: `Application web permettant d'utiliser le principe du "flipflap" sur des images.`,
            thumbnail: thumbnail._FLIPFLAP,
            keywords: ["flipflap", "arts", "divers", "images"],
        },
        Fractions: {
            id: "Fractions",
            title: "Fractions",
            url: "Fractions",
            description: `Banque d'outils pour travailler les fractions à l'école primaire (exercices, générateur, ...).`,
            thumbnail: thumbnail._FRACTIONS,
            keywords: [
                "fractions",
                "nombre",
                "numération",
                "mathématiques",
                "maths",
            ],
        },
        "Fractions/generateur": {
            id: "Fractions/generateur",
            title: "Fractions (Générateur)",
            url: "Fractions/generateur",
            description: `Générateur de représentations pour les fractions : quadrillage, pizza, lignes graduées.`,
            thumbnail: thumbnail._FRACTIONS_GENERATEUR,
            keywords: [
                "générateur",
                "fractions",
                "nombre",
                "numération",
                "mathématiques",
                "maths",
            ],
        },
        frise: {
            id: "frise",
            title: "Frises chronologiques",
            url: "frise",
            description: `Application web permettant de générer des images de frises chronologiques.`,
            thumbnail: thumbnail._FRISE,
            keywords: [
                "générateur",
                "frise",
                "histoire",
                "chronologie",
                "divers",
            ],
        },
        "frise-circulaire": {
            id: "frise-circulaire",
            title: "Frise temporelle circulaire",
            url: "frise-circulaire",
            description: `Application web permettant de générer des images de frises temporelles circulaires.`,
            thumbnail: thumbnail._FRISE_CIRCULAIRE,
            keywords: [
                "générateur",
                "frise",
                "circulaire",
                "histoire",
                "chronologie",
                "divers",
            ],
        },
        fusionddp: {
            id: "fusionddp",
            title: "Fusion de Didapages",
            url: "fusionddp",
            description: `Banque d'outils pour la fusion de petits livres interactifs créés avec Didapages.`,
            thumbnail: thumbnail._FUSIONDDP,
            keywords: [
                "didapages",
                "livres",
                "numériques",
                "fusion",
                "tuic",
                "divers",
            ],
        },
        fusionLignes: {
            id: "fusionLignes",
            title: "Fusion de lignes",
            url: "fusionLignes",
            description: `Application web permettant de concaténer les lignes d'un fichier texte. Par exemple, replacer le nom et le prénom sur une même ligne. (Aujourd'hui, je vous encourage à vous tourner vers Sublime Text qui doit permettre cela et encore plus...)`,
            thumbnail: thumbnail._FUSIONLIGNES,
            keywords: ["fusion", "tuic", "divers"],
        },
        gabuzomeu: {
            id: "gabuzomeu",
            title: "GaBuZoMeu",
            url: "gabuzomeu",
            description: `Application web permettant de travailler la numération Shadok ;).`,
            thumbnail: thumbnail._GABUZOMEU,
            keywords: [
                "gabuzomeu",
                "shadok",
                "maths",
                "mathématiques",
                "numération",
                "base 2",
            ],
        },
        graduations: {
            id: "graduations",
            title: "Graduations",
            url: "graduations",
            description: `Ligne graduée interactive à vidéo-projeter.`,
            thumbnail: thumbnail._GRADUATIONS,
            keywords: [
                "graduations",
                "maths",
                "mathématiques",
                "numération",
                "ligne",
                "graduée",
            ],
        },
        groupements: {
            id: "groupements",
            title: "Groupements",
            url: "groupements",
            description: `Application web permettant de travailler la numération et les opérations à l'école primaire par la manipulation (groupement, cassage,...) de différentes représentations des nombres.`,
            thumbnail: thumbnail._GROUPEMENTS,
            keywords: [
                "groupements",
                "maths",
                "mathématiques",
                "numération",
                "opération",
            ],
        },
        hashtagfrom: {
            id: "hashtagfrom",
            title: "HashtagFrom",
            url: "hashtagfrom",
            description: `Application web permettant de lister les messages Twitter envoyés par un abonné et contenant un mot-clé donné.`,
            thumbnail: thumbnail._HASHTAGFROM,
            keywords: ["hashtagfrom", "twitter", "divers"],
        },
        homophones: {
            id: "homophones",
            title: "Homophones",
            url: "homophones",
            description: `Application web permettant de générer au format pdf et d'imprimer des exercices sur les homophones.`,
            thumbnail: thumbnail._HOMOPHONES,
            keywords: [
                "homophones",
                "grammaire",
                "orthographe",
                "français",
                "générateur",
            ],
        },
        ImagesEtSons: {
            id: "ImagesEtSons",
            title: "Images et sons (surtout images)",
            url: "ImagesEtSons",
            description: `Banque d'images.`,
            thumbnail: thumbnail._IMAGESETSONS,
            keywords: ["images", "banque", "tuic", "divers"],
        },
        "images-sequentielles": {
            id: "images-sequentielles",
            title: "Images séquentielles",
            url: "images-sequentielles",
            description: `Application web permettant de proposer des images séquentielles en ligne à partir des ses propres images.`,
            thumbnail: thumbnail._IMAGES_SEQUENTIELLES,
            keywords: [
                "images",
                "séquentielles",
                "lecture",
                "compréhension",
                "français",
            ],
        },
        JeuxLecture: {
            id: "JeuxLecture",
            title: "Jeux de lecture",
            url: "JeuxLecture",
            description: `Banque de jeux en ligne permettant de se préparer et/ou de s'entraîner à la lecture.`,
            thumbnail: thumbnail._JEUX_LECTURE,
            keywords: ["jeux", "lecture", "portail", "français"],
        },
        JeuxMathematiques: {
            id: "JeuxMathematiques",
            title: "Jeux de mathématiques (Ancienne présentation)",
            url: "JeuxMathematiques",
            description: `Banque de jeux en ligne permettant de s'entraîner aux mathématiques.`,
            thumbnail: thumbnail._JEUX_MATHEMATIQUES,
            keywords: ["jeux", "mathématiques", "portail", "maths"],
        },
        "jeux-maths-1": {
            id: "jeux-maths-1",
            title: "Jeux de mathématiques (1)",
            url: "jeux-maths-1",
            description: `Banque de jeux en ligne permettant de s'entraîner aux mathématiques.`,
            thumbnail: thumbnail._JEUX_MATHEMATIQUES_1,
            keywords: ["jeux", "mathématiques", "portail", "maths"],
        },
        "jeux-maths-2": {
            id: "jeux-maths-2",
            title: "Jeux de mathématiques (2)",
            url: "jeux-maths-2",
            description: `Banque de jeux en ligne permettant de s'entraîner aux mathématiques.`,
            thumbnail: thumbnail._JEUX_MATHEMATIQUES_2,
            keywords: ["jeux", "mathématiques", "portail", "maths"],
        },
        labyrinthes: {
            id: "labyrinthes",
            title: "Les labyrinthes de MiCetF",
            url: "labyrinthes",
            description: `Activité en ligne permettant de parcourir des labyrinthes de plus en plus complexes en utilisant les touches directionnelles de son clavier ou le balayage avec le doigt sur un terminal tactile.`,
            thumbnail: thumbnail._LABYRINTHES,
            keywords: [
                "jeu",
                "maths",
                "mathématiques",
                "labyrinthe",
                "repérage",
            ],
        },
        "labyrinthes-pdf": {
            id: "labyrinthes-pdf",
            title: "Labyrinthes (Générateur)",
            url: "labyrinthes-pdf",
            description: `Application web permettant de générer des fiches d'exercices comprenant un ou plusieurs labyrinthes.`,
            thumbnail: thumbnail._LABYRINTHES_PDF,
            keywords: [
                "générateur",
                "jeu",
                "maths",
                "mathématiques",
                "labyrinthe",
                "repérage",
            ],
        },
        "la-bonne-image": {
            id: "la-bonne-image",
            title: "La bonne image",
            url: "la-bonne-image",
            description: `Application web permettant de travailler le vocabulaire en maternelle. L'élève doit cliquer sur l'image qui correspond au texte qu'il vient d'entendre.`,
            thumbnail: thumbnail._LA_BONNE_IMAGE,
            keywords: ["image", "jeu", "français", "vocabulaire"],
        },
        "le-bon-mot": {
            id: "le-bon-mot",
            title: "Le bon mot",
            url: "le-bon-mot",
            description: `Application web permettant de s'exercer en lecture au cycle 2.`,
            thumbnail: thumbnail._LE_BON_MOT,
            keywords: ["mot", "jeu", "français", "vocabulaire"],
        },
        LectureHeure: {
            id: "LectureHeure",
            title: "Lecture de l'heure",
            url: "LectureHeure",
            description: `Banque d'outils permettant de travailler la lecture de l'heure à l'école primaire (exercices, générateurs).`,
            thumbnail: thumbnail._LECTURE_HEURE,
            keywords: [
                "banque",
                "heure",
                "maths",
                "mathématiques",
                "mesure",
                "temps",
            ],
        },
        "LectureHeure/generateur": {
            id: "LectureHeure/generateur",
            title: "Lecture de l'heure (Générateur)",
            url: "LectureHeure/generateur",
            description: `Générateur d'horloges.`,
            thumbnail: thumbnail._LECTURE_HEURE_GENERATEUR,
            keywords: [
                "horloge",
                "heure",
                "maths",
                "mathématiques",
                "mesure",
                "temps",
                "générateur",
            ],
        },
        logitic: {
            id: "logitic",
            title: "Logitic - Logix",
            url: "logitic",
            description: `Application web permettant de conduire les activités proposées autour de Logix par D. Valentin pour les GS de maternelle.`,
            thumbnail: thumbnail._LOGITIC,
            keywords: [
                "logix",
                "logitic",
                "logique",
                "résolution",
                "problèmes",
                "maths",
                "mathématiques",
                "valentin",
            ],
        },
        logixourriel: {
            id: "logixourriel",
            title: "Logitic et communication",
            url: "logixourriel",
            description: `Application web permettant de conduire à distance les activités proposées autour de Logix par D. Valentin pour les GS de maternelle.`,
            thumbnail: thumbnail._LOGIXOURRIEL,
            keywords: [
                "twitter",
                "logix",
                "logitic",
                "logique",
                "résolution",
                "problèmes",
                "maths",
                "mathématiques",
                "valentin",
            ],
        },
        loto: {
            id: "loto",
            title: "Loto (Générateur)",
            url: "loto",
            description: `Application web permettant, à partir d'un corpus de mots ou d'images, de générer au format pdf et d'imprimer les pla et/ou les étiquettes (jetons) d'un jeu de loto.`,
            thumbnail: thumbnail._LOTO,
            keywords: ["loto", "jeu", "outil", "générateur", "divers"],
        },
        mastermind: {
            id: "mastermind",
            title: "Mastermind",
            url: "mastermind",
            description: `Jeu en ligne.`,
            thumbnail: thumbnail._MASTERMIND,
            keywords: [
                "mastermind",
                "jeu",
                "logique",
                "maths",
                "mathématiques",
            ],
        },
        "media-folder-generator": {
            id: "media-folder-generator",
            title: "Média Folder Générateur",
            url: "media-folder-generator",
            description: `Application web permettant la générations de dossiers de média destinés à un usage personnalisé des applications web "La Bonne Image" et "Ecoute et range".`,
            thumbnail: thumbnail._MEDIA_FOLDER_GENERATOR,
            keywords: [
                "media-folder-generator",
                "bonne",
                "image",
                "mot",
                "outils",
                "générateur",
                "médias",
                "divers",
            ],
        },
        "meme-indice": {
            id: "meme-indice",
            title: "Même indice",
            url: "meme-indice",
            description: `Application web permettant de générer au format pdf et d'imprimer des jeux de cartes pour travailler avec des élèves en difficulté d'apprentissage de la lecture : chaque paire de cartes à un indice commun (lettre, graphème,...) qu'il faut trouver.`,
            thumbnail: thumbnail._MEME_INDICE,
            keywords: ["même indice", "jeu", "carte", "français", "générateur"],
        },
        memory: {
            id: "memory",
            title: "Memory",
            url: "memory",
            description: `Application web permettant de jouer au mémory en ligne avec des jeux proposés ou avec des jeux générés à partir de son propre corpus d'images im génerateur).`,
            thumbnail: thumbnail._MEMORY,
            keywords: ["memory", "jeu", "mémoire", "divers"],
        },
        "memory/generateur": {
            id: "memory/generateur",
            title: "Memory (Générateur)",
            url: "memory/generateur",
            description: `Application web permettant de générer un memory à partir de son propre corpus d'images (cf. memory).`,
            thumbnail: thumbnail._MEMORY_GENERATEUR,
            keywords: ["memory", "jeu", "mémoire", "générateur", "divers"],
        },
        messagerie: {
            id: "messagerie",
            title: "Messagerie (défi)",
            url: "messagerie",
            description: `Application web permettant de générer les messages et les documents nécessaire à la conduite d'un rallye messagerie.`,
            thumbnail: thumbnail._MESSAGERIE,
            keywords: [
                "messagerie",
                "défi",
                "tuic",
                "communiquer",
                "générateur",
                "divers",
            ],
        },
        mesures: {
            id: "mesures",
            title: "Mesures (Périmètre et surface)",
            url: "mesures",
            description: `Application web permettant de mettre à l'épreuve les confusions qui peuvent se créer entre les notions de périmètre et de surface.`,
            thumbnail: thumbnail._MESURES,
            keywords: [
                "mesures",
                "périmètre",
                "surface",
                "maths",
                "mathématiques",
                "grandeurs",
                "géométrie",
            ],
        },
        minuterie: {
            id: "minuterie",
            title: "Minuterie",
            url: "minuterie",
            description: `Horloge virtuelle qui permet de visualiser le temps qu'il reste avant un événement distant de moins d'une heure.`,
            thumbnail: thumbnail._MINUTERIE,
            keywords: [
                "temps",
                "mesure",
                "reste",
                "timetimer",
                "maths",
                "mathématiques",
            ],
        },
        "mdp-gen": {
            id: "mdp-gen",
            title: "Mot de passe (Générateur)",
            url: "mdp-gen",
            description: `Générateur de mot de passe.`,
            thumbnail: thumbnail._MDP_GEN,
            keywords: [
                "mot",
                "passe",
                "password",
                "générateur",
                "outil",
                "divers",
            ],
        },
        montessori: {
            id: "montessori",
            title: "Montessori",
            url: "montessori",
            description: `Application web permettant de travailler la numération avec les cartons Montessori.`,
            thumbnail: thumbnail._MONTESSORI,
            keywords: [
                "montessori",
                "numération",
                "nombre",
                "maths",
                "mathématiques",
                "cartons",
            ],
        },
        mosaique: {
            id: "mosaique",
            title: "Mosaïque express",
            url: "mosaique",
            description: `Ce jeu interactif est inspiré du Rubik'S Race, jeu éducatif dont le but est de reproduire une mosaïque modèle de 9 cases (3x3) au centre d'un taquin de 25 cases (5x5).`,
            thumbnail: thumbnail._MOSAIQUE,
            keywords: [
                "mosaïque",
                "logique",
                "problème",
                "maths",
                "mathématiques",
                "jeu",
            ],
        },
        multiplication: {
            id: "multiplication",
            title: "Multiplication",
            url: "multiplication",
            description: `Jeu interactif permettant de s'exercer et de mémoriser les tables de multiplication.`,
            thumbnail: thumbnail._MULTIPLICATION,
            keywords: [
                "multiplication",
                "tables",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        NombrePense: {
            id: "NombrePense",
            title: "Nombre pensé",
            url: "NombrePense",
            description: `Tableau des nombres interactif conçu pour mettre les TIC au service de l'activité du nombre pensé. Le maître pense à un nombre. Par une série de questions, les élèves éliminent les nombres qui ne conviennent pas. Selon le scénario pédagogique envisagé par le professeur, le tableau peut être utilisé pour garder une trace des nombres éliminés, individuellement sur un ordinateur et/ou collectivement au moyen d'un vidéo-projecteur.`,
            thumbnail: thumbnail._NOMBRE_PENSE,
            keywords: ["numération", "nombres", "maths", "mathématiques"],
        },
        nombres: {
            id: "nombres",
            title: "Nombre (construction du)",
            url: "nombres",
            description: `Banque d'outils (étendue) permettant de travailler la construction du nombre à l'école primaire.`,
            thumbnail: thumbnail._NOMBRES,
            keywords: [
                "numération",
                "nombres",
                "maths",
                "mathématiques",
                "outils",
                "banque",
            ],
        },
        np2016: {
            id: "np2016",
            title: "Numérique et nouveaux programmes (2016)",
            url: "np2016",
            description: `Présentation des références au numérique dans les nouveaux programmes de 2016.`,
            thumbnail: thumbnail._NP2016,
            keywords: [
                "nouveaux",
                "programmes",
                "2016",
                "numérique",
                "présentation",
                "divers",
            ],
        },
        Numeration: {
            id: "Numeration",
            title: "Numération",
            url: "Numeration",
            description: `Banque d'outils (restreinte) permettant de travailler la numération à l'aide des représentations les plus utilisées à l'école primaire.`,
            thumbnail: thumbnail._NUMERATION,
            keywords: [
                "numération",
                "nombres",
                "maths",
                "mathématiques",
                "outils",
                "banque",
            ],
        },
        numop: {
            id: "numop",
            title: "Numération-Opération",
            url: "numop",
            description: `Application web permettant de travailler la numération et les opérations en manipulant les représentations les plus utilisées à l'école primaire.`,
            thumbnail: thumbnail._NUMOP,
            keywords: [
                "numop",
                "numération",
                "opérations",
                "nombres",
                "maths",
                "mathématiques",
                "outils",
            ],
        },
        ORLF: {
            id: "ORLF",
            title: "Observation réfléchie de la langue",
            url: "ORLF",
            description: `Application web proposant des exercices de grammaire, de conjugaison, d'orthographe ou de vocabulaire pour le cycle 3. Les élèves peuvent réaliser ces exercices en ligne. Les enseignants peuvent générer et imprimer ces exercices au format pdf.`,
            thumbnail: thumbnail._ORLF,
            keywords: [
                "orlf",
                "français",
                "grammaire",
                "maîtrise",
                "maitrise",
                "langue",
                "conjugaison",
                "orthographe",
                "conjugaison",
                "générateur",
            ],
        },
        operations: {
            id: "operations",
            title: "Opérations",
            url: "operations",
            description: `Banque d'outils permettant de générer au format pdf et d'imprimer des fiches d'exercices proposant des séries d'opérations posées.`,
            thumbnail: thumbnail._OPERATIONS,
            keywords: [
                "opérations",
                "calcul",
                "posé",
                "maths",
                "mathématiques",
                "générateur",
            ],
        },
        ordonner: {
            id: "ordonner",
            title: "Ordonner des nombres",
            url: "ordonner",
            description: `Application web permettant aux élèves de s'entraîner/évaluer au classement des nombres dans l'ordre croissant/décroissant.`,
            thumbnail: thumbnail._ORDONNER,
            keywords: [
                "ordonner",
                "ordre",
                "ranger",
                "croissant",
                "décroissant",
                "maths",
                "mathématiques",
                "numération",
            ],
        },
        "ordre-alpha": {
            id: "ordre-alpha",
            title: "Ordre alphabétique - La ruche des mots",
            url: "ordre-alpha",
            description: `Application web permettant de mémoriser l'orthographe lexicale des mots. L'enseignant peut s'incrire et gérer les listes de mots proposées à ses élèves.`,
            thumbnail: thumbnail._ORDRE_ALPHA,
            keywords: ["alphabet", "ordre", "vocabulaire", "français"],
        },
        orthographe: {
            id: "orthographe",
            title: "Orthographe - Entraînement orthographique",
            url: "orthographe",
            description: `Application web permettant de mémoriser l'orthographe lexicale des mots. L'enseignant peut s'incrire et gérer les listes de mots proposées à ses élèves.`,
            thumbnail: thumbnail._ORTHOGRAPHE,
            keywords: ["orthographe", "lexicale", "français"],
        },
        "ortho-lex": {
            id: "ortho-lex",
            title: "Orthographe Lexicale",
            url: "ortho-lex",
            description: `Pour chaque classe de la scolarité obligatoire (du CP à la 3ème), en s'appuyant sur l'échelle Dubois-Buysse, cette application web dicte des mots qu'il faut saisir au clavier.`,
            thumbnail: thumbnail._ORTHO_LEX,
            keywords: ["orthographe", "lexicale", "français"],
        },
        OutilsTICE: {
            id: "OutilsTICE",
            title: "Outils TICE",
            url: "OutilsTICE",
            description: `Banque d'outils divers et variés.`,
            thumbnail: thumbnail._OUTILSTICE,
            keywords: ["outils", "tice", "divers"],
        },
        papota2: {
            id: "papota2",
            title: "P@pot'à 2",
            url: "papota2",
            description: `Application web "expérimentale" permettant à deux personnes de communiquer en temps réel.`,
            thumbnail: thumbnail._PAPOTA2,
            keywords: ["communiquer", "prototype", "divers"],
        },
        parachute: {
            id: "parachute",
            title: "Parachute",
            url: "parachute",
            description: `Jeu interactif permettant de travailler les nombres décimaux outour d'une ligne graduée.`,
            thumbnail: thumbnail._PARACHUTE,
            keywords: [
                "parachute",
                "nombres",
                "décimaux",
                "numération",
                "décimale",
                "maths",
                "mathématiques",
            ],
        },
        parapente: {
            id: "parapente",
            title: "Parapente",
            url: "parapente",
            description: `Jeu interactif permettant de travailler les nombres entiers autour d'une ligne graduée.`,
            thumbnail: thumbnail._PARAPENTE,
            keywords: [
                "parapente",
                "nombres",
                "entiers",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        "parcours-de-phrases": {
            id: "parcours-de-phrases",
            title: "Parcours de phrases (Orthographe)",
            url: "parcours-de-phrases",
            description: `Jeu interactif dont le but est de retrouver dans un tableau le parcours (linéaire) qui permet de reconstruire une phrase juste.`,
            thumbnail: thumbnail._PARCOURS_DE_PHRASES,
            keywords: ["parcours de phrases", "français", "orthographe"],
        },
        parking: {
            id: "parking",
            title: "Parking",
            url: "parking",
            description: `Version mobile du jeu interactif Embouteillages et qui reprend l'activité du même nom proposée par D. Valentin pour les GS.`,
            thumbnail: thumbnail._PARKING,
            keywords: [
                "embouteillages",
                "parking",
                "logique",
                "résolution",
                "problèmes",
                "maths",
                "mathématiques",
                "valentin",
            ],
        },
        pense: {
            id: "pense",
            title: "Pense, pense..., le nombre pensé",
            url: "pense",
            description: `Jeu interactif dont le but est de retrouver le plus rapidement possible un nombre mystérieux. A chaque proposition, l'application répond par "Trop petit" ou "Trop grand".`,
            thumbnail: thumbnail._PENSE,
            keywords: [
                "numération",
                "nombres",
                "maths",
                "mathématiques",
                "pensé",
            ],
        },
        phonologie: {
            id: "phonologie",
            title: "Phonologie",
            url: "phonologie",
            description: `Application web proposant des exercices de phonologie pour des élèves de CP. Les élèves peuvent réaliser ces exercices en ligne. Les enseignants peuvent générer et imprimer ces exercices au format pdf.`,
            thumbnail: thumbnail._PHONOLOGIE,
            keywords: [
                "phonologie",
                "lecture",
                "sons",
                "français",
                "syllabes",
                "générateur",
            ],
        },
        phrases: {
            id: "phrases",
            title: "Phrases à reconstituer",
            url: "phrases",
            description: `Application web permettant de créer des exercices personnalisés de remise en ordre de phrases.`,
            thumbnail: thumbnail._PHRASES,
            keywords: ["phrases", "grammaire", "syntaxe", "français"],
        },
        picbille: {
            id: "picbille",
            title: "Picbille",
            url: "picbille",
            description: `Application web permettant de créer des images de boites Picbilles.`,
            thumbnail: thumbnail._PICBILLE,
            keywords: [
                "picbille",
                "nombre",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        picturetopuzzle: {
            id: "picturetopuzzle",
            title: "Picture To Puzzle",
            url: "picturetopuzzle",
            description: `Application web permettant de générer un puzzle en ligne à partir d'une image téléchargée.`,
            thumbnail: thumbnail._PICTURETOPUZZLE,
            keywords: ["picturetopuzzle", "puzzle", "générateur", "divers"],
        },
        PortraitChinois: {
            id: "PortraitChinois",
            title: "Petite Fabrique à Portraits Chinois",
            url: "PortraitChinois",
            description: `Application web permettant la créattion de petits livres interactifs sur le thème des "Portraits chinois".`,
            thumbnail: thumbnail._PORTRAITCHINOIS,
            keywords: [
                "écrit",
                "histoires",
                "portraits",
                "chinois",
                "fabrique",
                "français",
            ],
        },
        Problemes: {
            id: "Problemes",
            title: "Problèmes pour l'école",
            url: "Problemes",
            description: `Banque de problèmes pour l'école primaire. Les élèves peuvent résoudre ces problèmes en ligne. L'enseignant peut générer au format pdf et imprimer des fiches de 4 problèmes.`,
            thumbnail: thumbnail._PROBLEMES,
            keywords: [
                "problèmes",
                "résolution",
                "typologie",
                "vergnaud",
                "générateur",
                "maths",
                "mathématiques",
            ],
        },
        ProdEcrits: {
            id: "ProdEcrits",
            title: "Production d'écrits",
            url: "ProdEcrits",
            description: `Banque d'outils d'aide à la production d'écrits.`,
            thumbnail: thumbnail._PRODECRITS,
            keywords: ["écrits", "production", "outils", "banque", "français"],
        },
        puissance10: {
            id: "puissance10",
            title: "Puissance 10",
            url: "puissance10",
            description: `Multiplier ou diviser par 10, 100 ou 1000. Observation.`,
            thumbnail: thumbnail._PUISSANCE10,
            keywords: [
                "multiplier",
                "10",
                "100",
                "1000",
                "produit",
                "diviser",
                "puissance",
                "maths",
                "mathématiques",
            ],
        },
        qrcode: {
            id: "qrcode",
            title: "QR Code (Générateur)",
            url: "qrcode",
            description: `Application web permettant la génération d'un QR Code à partir d'une URL.`,
            thumbnail: thumbnail._QRCODE,
            keywords: ["qrcode", "outil", "générateur", "divers"],
        },
        quadrillage: {
            id: "quadrillage",
            title: "Quadrillage - Se repérer sur un quadrillage",
            url: "quadrillage",
            description: `Application web permettant de proposer une activité de repérage sur quadrillage à des élèves de cycle 2.`,
            thumbnail: thumbnail._QUADRILLAGE,
            keywords: [
                "quadrillage",
                "repérage",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        "rallye-lecture": {
            id: "rallye-lecture",
            title: "Rallye lecture",
            url: "rallye-lecture",
            description: `Application web permettant de générer au format pdf et d'imprimer des fiches de lecture.`,
            thumbnail: thumbnail._RALLYE_LECTURE,
            keywords: ["rallye", "lecture", "français", "générateur"],
        },
        recadrer: {
            id: "recadrer",
            title: "Recadrer une image.",
            url: "recadrer",
            description: `Application web permettant de recadrer une image sans passer par un logiciel de retouche. Bien utile pour les images utilisées avec les différents générateurs proposés sur ce site (loto, symbole commun, vocatego, écoute et range, la bonne image, ....)`,
            thumbnail: thumbnail._RECADRER,
            keywords: ["image", "recadrer", "outil", "tuic", "divers"],
        },
        reperage: {
            id: "reperage",
            title: "Repérage sur quadrillage - La chasse au nuage",
            url: "reperage",
            description: `Jeu interactif permettant de s'entraîner aux déplacements sur un quadrillage.`,
            thumbnail: thumbnail._REPERAGE,
            keywords: [
                "quadrillage",
                "repérage",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        "reproduction-sur-quadrillage": {
            id: "reproduction-sur-quadrillage",
            title: "Reproduction sur quadrillage",
            url: "reproduction-sur-quadrillage",
            description: `Application web proposant des dessins à reproduire en utilisant un quadrillage (ou un pointage).`,
            thumbnail: thumbnail._RSQ,
            keywords: [
                "quadrillage",
                "reproduction",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        rsqgenerateur: {
            id: "rsqgenerateur",
            title: "Reproduction sur quadrillage (Générateur)",
            url: "rsqgenerateur",
            description: `Application web permettant de créer des dessins à reproduire en utilisant un quadrillage (ou un pointage).`,
            thumbnail: thumbnail._RSQGENERATEUR,
            keywords: [
                "quadrillage",
                "reproduction",
                "générateur",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        "rounded-word": {
            id: "rounded-word",
            title: "Rounded Word",
            url: "rounded-word",
            description: `Application web proposant de lire des mots écrits en rond. Les mots sont écrits dans le sens des aiguilles d'une montre mais aussi parfois en sens inverse.
Le jeu est multijoueurs et peut donner lieu à un défi en ligne entre élèves ou entre classes.`,
            thumbnail: thumbnail._ROUNDED_WORD,
            keywords: ["rounded", "word", "lecture", "mots", "jeu", "français"],
        },
        "rounded-word-cards": {
            id: "rounded-word-cards",
            title: "Rounded Word (Générateur)",
            url: "rounded-word-cards",
            description: `Application web permettant de générer un jeu de cartes basé sur le même principe que le jeu en ligne précédent (Rounded Word).`,
            thumbnail: thumbnail._ROUNDED_WORD_CARDS,
            keywords: [
                "rounded",
                "word",
                "lecture",
                "mots",
                "jeu",
                "français",
                "générateur",
                "cartes",
            ],
        },
        reussites: {
            id: "reussites",
            title: "Réussite des nombres (CP/CE1)",
            url: "reussites",
            description: `Jeu interactif dont l'objectif est de replacer des nombres à leur place sur une file numérique.`,
            thumbnail: thumbnail._REUSSITES,
            keywords: [
                "réussite",
                "nombres",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        robots: {
            id: "robots",
            title: "Robots (La fabrique de)",
            url: "robots",
            description: `Jeu interactif dont le but est de finir la copie d'un robot en utilisant des carrés de couleurs stockés dans un magasin. Destinée à des élèves de GS/CP, cette activité de numération vise à faire disparaître la procédure de correspondance un à un au profit du dénombrement.`,
            thumbnail: thumbnail._ROBOTS,
            keywords: [
                "robots",
                "nombres",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        "ruche-mots": {
            id: "ruche-mots",
            title: "Ruche des mots",
            url: "ruche-mots",
            description: `Jeu interactif dont le but est de suivre l'ordre alphabétique pour traverser une ruche.`,
            thumbnail: thumbnail._RUCHE_MOTS,
            keywords: [
                "ruche",
                "mots",
                "alphabet",
                "ordre",
                "vocabulaire",
                "français",
            ],
        },
        "ruche-nombres": {
            id: "ruche-nombres",
            title: "Ruche des nombres",
            url: "ruche-nombres",
            description: `Jeu interactif dont le but est de suivre l'ordre alphabétique pour traverser une ruche.`,
            thumbnail: thumbnail._RUCHE_NOMBRES,
            keywords: [
                "ruche",
                "nombres",
                "ordre",
                "numération",
                "maths",
                "mathématiques",
            ],
        },
        sciences: {
            id: "sciences",
            title: "Sciences - Le thermomètre",
            url: "sciences",
            description: `Jeu interactif permettant de s'exercer à la lecture de la température sur un thermomètre à mercure.`,
            thumbnail: thumbnail._SCIENCES,
            keywords: [
                "thermomètre",
                "sciences",
                "mesure",
                "découverte",
                "divers",
            ],
        },
        scrabble: {
            id: "scrabble",
            title: "Scrabble",
            url: "scrabble",
            description: `Plateau de scrabble pour conduire des activités de scrabble scolaire (Scrabble duplicate - plateau collectif vidéoprojeté, plateau individuel).`,
            thumbnail: thumbnail._SCRABBLE,
            keywords: ["scrabble", "français", "jeu", "plateau"],
        },
        "sept-familles": {
            id: "sept-familles",
            title: "Sept familles (Générateur)",
            url: "sept-familles",
            description: `Application web qui permet de générer un jeu de sept familles au format pdf à partir de son propre corpus d'images et/ou de mots.`,
            thumbnail: thumbnail._SEPT_FAMILLES,
            keywords: [
                "sept",
                "familles",
                "générateur",
                "vocabulaire",
                "français",
                "jeu",
                "cartes",
            ],
        },
        sig: {
            id: "sig",
            title: "S.I.G.",
            url: "sig",
            description: `Application web permettant de se construire une première représentattion géographique du monde (Système d'Informations Géographiques).`,
            thumbnail: thumbnail._SIG,
            keywords: ["sig", "géographie", "carte", "divers"],
        },
        souris: {
            id: "souris",
            title: "Souris - Les rois de la souris",
            url: "souris",
            description: `Jeu interactif permettant de s'exercer au maniement de la souris.`,
            thumbnail: thumbnail._SOURIS,
            keywords: ["souris", "rois", "tuic", "saisie", "divers"],
        },
        "simulation-salaire": {
            id: "simulation-salaire",
            title: 'Simulation d\'un bulletin de paye "PE"',
            url: "simulation-salaire",
            description: `Application web permettant quelques simulations autour du salaire d'un PE.`,
            thumbnail: thumbnail._SIMULATION_SALAIRE,
            keywords: ["salaire", "simulation", "outil", "divers"],
        },
        superpositions: {
            id: "superpositions",
            title: "Superpositions",
            url: "superpositions",
            description: `Travail de géométrie sur les différents plans, reconnaître des figures superposées, décrire une figure en superposant les formes, dictées, au cycle2`,
            thumbnail: thumbnail._SUPERPOSITIONS,
            keywords: [
                "géométrie",
                "superpositions",
                "figures",
                "plans",
                "mathématiques",
            ],
        },
        Symetrie: {
            id: "Symetrie",
            title: "Symétrie",
            url: "Symetrie",
            description: `Jeu interactif permettant de travailler la symétrie axiale.`,
            thumbnail: thumbnail._SYMETRIE,
            keywords: [
                "symétrie",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        ssq: {
            id: "ssq",
            title: "Symétrie sur quadrillage",
            url: "ssq",
            description: `Application web permettant de s'exercer au tracé de figures géométriques sur un quadrillage.`,
            thumbnail: thumbnail._SSQ,
            keywords: [
                "quadrillage",
                "symétrie",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        ssqgenerateur: {
            id: "ssqgenerateur",
            title: "Symétrie sur quadrillage (Générateur)",
            url: "ssqgenerateur",
            description: `Application web permettant de créer des exercices de tracé de figures géométriques sur quadrillage.`,
            thumbnail: thumbnail._SSQGENERATEUR,
            keywords: [
                "quadrillage",
                "symétrie",
                "générateur",
                "géométrie",
                "espace",
                "maths",
                "mathématiques",
            ],
        },
        sudoku: {
            id: "sudoku",
            title: "Sudoku (Générateur)",
            url: "sudoku",
            description: `Générateur de Sudoku en ligne.`,
            thumbnail: thumbnail._SUDOKU,
            keywords: [
                "sudoku",
                "logique",
                "maths",
                "mathématiques",
                "problèmes",
            ],
        },
        "symbole-commun": {
            id: "symbole-commun",
            title: "Symbole Commun (Générateur)",
            url: "symbole-commun",
            description: `Application web permettant de chercher en ligne le symbole commun entre deux cartes mais surtout de générer et imprimer des jeux de cartes personnalisés en utilisant ses propres images. Cet outil est très intéressant pour travailler le langage avec des élèves de cycle 1.`,
            thumbnail: thumbnail._SYMBOLE_COMMUN,
            keywords: [
                "dobble",
                "symbole",
                "langage",
                "jeu",
                "cartes",
                "générateur",
                "divers",
            ],
        },
        TablesAddition: {
            id: "TablesAddition",
            title: "Tables d'addition",
            url: "TablesAddition",
            description: `Jeu interactif permettant de mémoriser les tables d'addition.`,
            thumbnail: thumbnail._TABLES_ADDITION,
            keywords: [
                "addition",
                "tables",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        TablesDivision: {
            id: "TablesDivision",
            title: "Tables de division",
            url: "TablesDivision",
            description: `Jeu interactif permettant de mémoriser les tables de division.`,
            thumbnail: thumbnail._TABLES_DIVISION,
            keywords: [
                "division",
                "tables",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        TablesMultiplication: {
            id: "TablesMultiplication",
            title: "Tables de multiplication",
            url: "TablesMultiplication",
            description: `Jeu interactif permettant de mémoriser les tables de multiplication.`,
            thumbnail: thumbnail._TABLES_MULTIPLICATION,
            keywords: [
                "multiplication",
                "tables",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        TablesSoustraction: {
            id: "TablesSoustraction",
            title: "Tables de soustraction",
            url: "TablesSoustraction",
            description: `Jeu interactif permettant de mémoriser les tables de soustraction.`,
            thumbnail: thumbnail._TABLES_SOUSTRACTION,
            keywords: [
                "soustraction",
                "tables",
                "calcul",
                "maths",
                "mathématiques",
            ],
        },
        tempsquireste: {
            id: "tempsquireste",
            title: "Temps qu'il reste",
            url: "tempsquireste",
            description: `Horloge virtuelle qui permet de visualiser le temps qu'il reste avant un événement distant de moins d'une heure.`,
            thumbnail: thumbnail._TEMPSQUIRESTE,
            keywords: [
                "temps",
                "mesure",
                "reste",
                "timetimer",
                "maths",
                "mathématiques",
            ],
        },
        thermometre: {
            id: "thermometre",
            title: "Thermomètre",
            url: "thermometre",
            description: `Thermomètre virtuel interactif.`,
            thumbnail: thumbnail._THERMOMETRE,
            keywords: [
                "thermomètre",
                "sciences",
                "mesure",
                "découverte",
                "divers",
            ],
        },
        vehicules: {
            id: "vehicules",
            title: "Véhicules",
            url: "vehicules",
            description: `Application web permettant d'expérimenter le problème des véhicules (Des voitures et des vélos sont stationnés sur un parking. On connait le nombre de véhicules et le nombre de roues, mais on ne connait pas le détail. A toi de retrouver le nombre de voitures et de vélos.)`,
            thumbnail: thumbnail._VEHICULES,
            keywords: [
                "véhicules",
                "problème",
                "maths",
                "mathématiques",
                "recherche",
            ],
        },
        vocatego: {
            id: "vocatego",
            title: "VoCaTeGo (Générateur)",
            url: "vocatego",
            description: `Vous jouez à Cache Tomate pour travailler le vocabulaire avec vos élèves ? Les catégories proposées dans le jeu ne vous suffisent plus ? Vous aimeriez en ajouter de nouvelles plus en rapport avec les thèmes actuels de la classe ? Cette application web est faite pour vous...`,
            thumbnail: thumbnail._VOCATEGO,
            keywords: [
                "vocatego",
                "générateur",
                "cartes",
                "vocabulaire",
                "français",
            ],
        },
        "video-tag": {
            id: "video-tag",
            title: "Vidéo Tag",
            url: "video-tag",
            description: `Application web permettant de générer automatiquement le code avec la balise <video> nécessaire à l'insertion d'une vidéo dans une page html5.`,
            thumbnail: thumbnail._VIDEO_TAG,
            keywords: [
                "video",
                "balise",
                "tag",
                "générateur",
                "outil",
                "html5",
                "divers",
            ],
        },
        wpprezi: {
            id: "wpprezi",
            title: "WP-Prezi",
            url: "wpprezi",
            description: `Application web permettant de générer automatiquement le shortcode nécessaire à l'insertion d'un Prezi dans un article sur un plog de la plateforme WordPress.com.`,
            thumbnail: thumbnail._WPPREZI,
            keywords: [
                "wordpress",
                "prezi",
                "générateur",
                "outil",
                "shortcode",
                "divers",
            ],
        },
        ytsearch: {
            id: "ytsearch",
            title: "Youtube (SafeSearch Strict)",
            url: "ytsearch",
            description: `Application web permettant une recherche rapide sur Youtube avec le mode safeSearch à strict.`,
            thumbnail: thumbnail._YTSEARCH,
            keywords: ["youtube", "recherche", "outil", "divers"],
        },
        youtube: {
            id: "youtube",
            title: "Youtube (Les vidéos de MiCetF)",
            url: "youtube",
            description: `Chaîne YouTube de MiCetF.`,
            thumbnail: thumbnail._YOUTUBE,
            keywords: ["youtube", "chaîne", "vidéos", "tutoriels", "divers"],
        },
        "4pions": {
            id: "4pions",
            title: "4 pions",
            url: "4pions",
            description: `Version mobile du jeu interactif Quatre pions et qui reprend l'activité du même nom proposée par D. Valentin pour les GS.`,
            thumbnail: thumbnail._4PIONS,
            keywords: [
                "pions",
                "orientation",
                "espace",
                "maths",
                "mathématiques",
                "problème",
                "résolution",
                "valentin",
            ],
        },
    },
    allIds: [
        "abaque",
        "abataquin",
        "acrostiche",
        "addigrille",
        "addition",
        "alphabet",
        "anagrammes",
        "angles",
        "animations",
        "arborescence",
        "ardoise",
        "awarhol",
        "audio-tag",
        "barres-doigts",
        "bataille",
        "blog",
        "boulierHTML5",
        "boulier",
        "rcn2017",
        "calculmental",
        "cambridge",
        "cartapoints",
        "alea-cartes",
        "chateau",
        "chemins-de-phrases",
        "choixpeau",
        "cibles",
        "classement",
        "clavier",
        "cologrilles",
        "cologrillesgenerateur",
        "complements",
        "compter",
        "Compteur",
        "conjugaison",
        "Conversions",
        "conversion",
        "conversion2",
        "CourseAu21",
        "decimaux",
        "Denombrement",
        "Didapages",
        "divisator",
        "Dominos",
        "dictee",
        "dicteenombres",
        "differences",
        "discrimination",
        "eAcrostiches",
        "eDidaFusion",
        "ecrans-ipad",
        "Embouteillages",
        "Etiquettes",
        "eEtiquettes",
        "ecoute-et-range",
        "FaBriCaMo",
        "FabriqueHistoires",
        "FabriquePourquoiParceque",
        "Flipflap",
        "Fractions",
        "Fractions/generateur",
        "frise",
        "frise-circulaire",
        "fusionddp",
        "fusionLignes",
        "gabuzomeu",
        "graduations",
        "groupements",
        "hashtagfrom",
        "homophones",
        "ImagesEtSons",
        "images-sequentielles",
        "JeuxLecture",
        "JeuxMathematiques",
        "jeux-maths-1",
        "jeux-maths-2",
        "labyrinthes",
        "labyrinthes-pdf",
        "la-bonne-image",
        "le-bon-mot",
        "LectureHeure",
        "LectureHeure/generateur",
        "logitic",
        "logixourriel",
        "loto",
        "mastermind",
        "media-folder-generator",
        "meme-indice",
        "memory",
        "memory/generateur",
        "messagerie",
        "mesures",
        "minuterie",
        "mdp-gen",
        "montessori",
        "mosaique",
        "multiplication",
        "NombrePense",
        "nombres",
        "np2016",
        "Numeration",
        "numop",
        "ORLF",
        "operations",
        "ordonner",
        "ordre-alpha",
        "orthographe",
        "ortho-lex",
        "OutilsTICE",
        "papota2",
        "parachute",
        "parapente",
        "parcours-de-phrases",
        "parking",
        "pense",
        "phonologie",
        "phrases",
        "picbille",
        "picturetopuzzle",
        "PortraitChinois",
        "Problemes",
        "ProdEcrits",
        "puissance10",
        "qrcode",
        "quadrillage",
        "rallye-lecture",
        "recadrer",
        "reperage",
        "reproduction-sur-quadrillage",
        "rsqgenerateur",
        "rounded-word",
        "rounded-word-cards",
        "reussites",
        "robots",
        "ruche-mots",
        "ruche-nombres",
        "sciences",
        "scrabble",
        "sig",
        "souris",
        "sept-familles",
        "simulation-salaire",
        "superpositions",
        "Symetrie",
        "ssq",
        "ssqgenerateur",
        "sudoku",
        "symbole-commun",
        "TablesAddition",
        "TablesDivision",
        "TablesMultiplication",
        "TablesSoustraction",
        "tempsquireste",
        "thermometre",
        "vehicules",
        "vocatego",
        "video-tag",
        "wpprezi",
        "ytsearch",
        "youtube",
        "4pions",
    ],
};
